#! /usr/bin/env bash

# Auto-detect battery (BAT0, BAT1, etc.)
BAT=$(ls /sys/class/power_supply | grep -m1 BAT)

cap="/sys/class/power_supply/$BAT/capacity"

# Print initial value
echo "$(cat "$cap")"

